---
cog_bundle_version: 3
name: cfn
description: "AWS CloudFormation"
version: "0.0.1"
docker:
  image: cogcmd/aws-cfn
  tag: "0.0.1"
commands:
  template:
    executable: /home/bundle/cog-command
    description: "Pass through only the first N results"
    documentation: |
      format:head [count] - pass through the first [count] results

      `count` must be a non-zero positive integer. The default value
      is `10` if none is provided.

    rules:
    - "when command is cfn:template must have cfn:view"
permissions:
  - cfn:view
