---
cog_bundle_version: 4
name: cfn
description: AWS CloudFormation
version: 0.0.95
docker:
  image: cogcmd/aws-cfn
  tag: 0.0.8
commands:
  template-list:
    executable: "/home/bundle/cog-command"
    description: List available CloudFormation templates
    rules:
    - must have cfn:template
  template-show:
    executable: "/home/bundle/cog-command"
    description: Show summary information for a CloudFormation template
    arguments: "<template_name> | -s <stack_name>"
    options:
      stack:
        type: bool
        required: false
        short_flag: s
        description: Show template information for the specified stack.
    rules:
    - must have cfn:template
  stack-create:
    executable: "/home/bundle/cog-command"
    description: Creates a new stack based on an existing template and returns the newly created stack.
    arguments: "<stack_name> <template_name>"
    options:
      param:
        type: list
        required: false
        short_flag: p
        description: Key-value pairs specified as 'key=value', that specify input parameters for your stack. Can be specified multiple times.
      tag:
        type: list
        required: false
        short_flag: t
        description: Key-value pairs to associate with this stack. Can be specified multiple times.
      policy:
        type: string
        required: false
        short_flag: o
        description: Stack policy name.
      notify:
        type: list
        required: false
        short_flag: n
        description: The Simple Notification Service (SNS) topic ARNs to publish stack related events. Can be specified multiple times.
      on-failure:
        type: string
        required: false
        short_flag: f
        description: Determines what action will be taken if stack creation fails. Can be one of: rollback, delete or keep.
      timeout:
        type: int
        required: false
        short_flag: e
        description: The amount of time, specified in minutes, that can pass before the stack status becomes CREATE_FAILED.
      capabilities:
        type: list
        required: false
        short_flag: c
        description: Can be one of: iam or named_iam.
    rules:
    - must have cfn:stack
  stack-delete:
    executable: "/home/bundle/cog-command"
    description: Deletes a stack.
    arguments: "<stack_name>"
    rules:
    - must have cfn:stack
  stack-events:
    executable: "/home/bundle/cog-command"
    description: Lists events for a stack. Returns all stack related events for a
      specified stack in reverse chronological order.
    arguments: "<stack_name>"
    rules:
    - must have cfn:stack
  stack:
    executable: "/home/bundle/cog-command"
    description: Manage CloudFormation stacks
    options:
      help:
        type: bool
        required: false
        short_flag: h
      filter:
        type: list
        required: false
      limit:
        type: int
        required: false
      param:
        type: list
        required: false
        short_flag: p
      tag:
        type: list
        required: false
        short_flag: t
      policy:
        type: string
        required: false
        short_flag: o
      notify:
        type: list
        required: false
        short_flag: n
      on-failure:
        type: string
        required: false
        short_flag: f
      timeout:
        type: int
        required: false
        short_flag: e
      capabilities:
        type: list
        required: false
        short_flag: c
    rules:
    - must have cfn:stack
  changeset:
    executable: "/home/bundle/cog-command"
    description: Manage CloudFormation changesets
    documentation: cfn:changeset <subcommand> [options] - Manage CloudFormation changesets
    options:
      help:
        type: bool
        required: false
        short_flag: h
      param:
        type: list
        required: false
        short_flag: p
      tag:
        type: list
        required: false
        short_flag: t
      template:
        type: string
        required: false
        short_flag: m
      notify:
        type: list
        required: false
        short_flag: n
      capabilities:
        type: list
        required: false
        short_flag: c
      description:
        type: string
        required: false
        short_flag: d
      changeset-name:
        type: string
        required: false
    rules:
    - must have cfn:changeset
permissions:
- cfn:stack
- cfn:changeset
- cfn:template
templates:
  template_list:
    body: |
      ~attachment title="CloudFormation Templates" color="#1E5775"~~end~
      ~attachment color="#2681A3"~
      ~each var=$results as=template~
      • ~$template.name~
      ~end~
      ~end~
  template_show:
    body: |
      ~attachment title="CloudFormation Template Details" color="#1E5775" title_link=$results[0].source~~end~

      ~attachment title="Resource Types" color="#2681A3"~
      ~each var=$results[0].resource_types as=item~
      • ~$item~
      ~end~
      ~end~

      ~attachment title="Parameters" color="#2681A3"~
      | Key | Type | Default | Allowed |
      |-----|------|---------|---------|
      ~each var=$results[0].parameters as=item~
      | ~$item.parameter_key~ | ~$item.parameter_type~ | ~$item.default_value~ |  ~join var=$item.parameter_constraints.allowed_values as=allowed_values with=", "~~$allowed_values~~end~ |
      ~end~
      ~end~
  stack_show:
    body: |
      ~each var=$results as=stack~
      ~attachment title=$stack.stack_name color="mediumblue"~
      ~$stack.stack_status~
      ~end~
      ~attachment title="Parameters" color="darkblue"~
      | Key | Value |
      |-----|-------|
      ~each var=$stack.parameters as=param~
      | ~$param.parameter_key~ | ~$param.parameter_value~ |
      ~end~
      ~end~
      ~end~
  stack_event_list:
    body: |
      ~attachment title="Events for stack"~
      | Timestamp | Status | Logical Resource ID |
      |-----------|--------|---------------------|
      ~each var=$results as=event~
      | ~$event.timestamp~ | ~$event.resource_status~ | ~$event.logical_resource_id~ |
      ~end~
      ~end~
