---
cog_bundle_version: 3
name: cfn
description: "AWS CloudFormation"
version: "0.0.2"
docker:
  image: cogcmd/aws-cfn
  tag: "0.0.2"
commands:
  template:
    executable: /home/bundle/cog-command
    description: "Pass through only the first N results"
    documentation: |
      format:head [count] - pass through the first [count] results

      `count` must be a non-zero positive integer. The default value
      is `10` if none is provided.

    rules:
    - "must have cfn:view"
  create:
    executable: /home/bundle/cog-command
    description: "Deploy a new CloudFormation stack using an existing Template"
    options:
      param:
        type: list
        required: false
        short_flag: p
      tag:
        type: list
        required: false
        short_flag: t
      policy:
        type: string
        required: false
        short_flag: o
      notify:
        type: list
        required: false
        short_flag: n
      on-failure:
        type: string
        required: false
        short_flag: f
      timeout:
        type: int
        required: false
        short_flag: e
      capabilities:
        type: list
        required: false
        short_flag: c
    rules:
      - "must have cfn:create"
permissions:
  - cfn:view
  - cfn:create
